---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Install NTP
    apt: package=ntp,ntpdate state=present update_cache=yes

  - name: Copy over NTP config
    template: src=ntp.conf dest=/etc/ntp.conf

